### ISSUE TITLE
not able to build sscep

### ISSUE THREAD

**Issue by aberger1** [certnanny/sscep#41]
Hello,

I'm sorry, but I'm a complete newbie in compiling tools from source.
Until now I've used a compiled version of sscep 0.5 which I found in internet.
It was running fine on Ubuntu 14.04 but after upgrading to 14.10 I get
a segmentation fault.

I downloaded actual sscep-develop from this site and tried to compile sscep from source but I get
the message:

(I moved to "Linux" - Folder of sscep-develop and entered "make")
 "No rule to make target 'sscep.o', needed by 'sscep_static'" . Schluss

I'm completely lost which path and which version I have to use for parameter
OPENSSL in Linux\Makefile

Thanks a lot for your help

Toni

**Comment by fabiostrada77** [comment]
Hi, 
I trying to compile client sscep, but I don't able. I executed "./configure" and then "make".  I have this error:

gcc -Wall -O  -I ../openssl/include    -c -o sscep.o sscep.c
In file included from sscep.h:22:0,
                 from sscep.c:11:
configuration.h:13:26: fatal error: openssl/conf.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'sscep.o' failed
make: *** [sscep.o] Error 1

How Can I solve it?
Are there others tools to install?

Thanks...

**Comment by tscherf** [comment]
You need to install openssl-devel.

**Comment by fabiostrada77** [comment]
Unfortunately, I don't able to install openssl-devel. 
As regards sscep client, I modified the Makefile: I updated the OPENSSL Path, with Url of my openssl (I downloaded it , by git).

**Comment by axhameed** [comment]
Hi,
I am trying to compile sscep but have not had any luck. This is what I am doing:
$ ./Configure
Configuring for Linux...
$ make package
gcc -Wall -O  -I ../openssl/include    -c -o sscep.o sscep.c
gcc -Wall -O  -I ../openssl/include    -c -o init.o init.c
gcc -Wall -O  -I ../openssl/include    -c -o net.o net.c
gcc -Wall -O  -I ../openssl/include    -c -o sceputils.o sceputils.c
gcc -Wall -O  -I ../openssl/include    -c -o pkcs7.o pkcs7.c
pkcs7.c: In function âpkcs7_wrapâ:
pkcs7.c:222: warning: value computed is not used
pkcs7.c:324: warning: value computed is not used
pkcs7.c: In function âpkcs7_verify_unwrapâ:
pkcs7.c:396: warning: value computed is not used
pkcs7.c: In function âpkcs7_unwrapâ:
pkcs7.c:558: warning: value computed is not used
pkcs7.c:772: warning: value computed is not used
pkcs7.c: In function âget_signed_attributeâ:
pkcs7.c:867: warning: implicit declaration of function âASN1_STRING_get0_dataâ
pkcs7.c:867: warning: passing argument 2 of âmemcpyâ makes pointer from integer without a cast
/usr/include/string.h:44: note: expected âconst void * __restrict__â but argument is of type âintâ
gcc -Wall -O  -I ../openssl/include    -c -o ias.o ias.c
gcc -Wall -O  -I ../openssl/include    -c -o fileutils.o fileutils.c
gcc -Wall -O  -I ../openssl/include    -c -o configuration.o configuration.c
gcc -Wall -O  -I ../openssl/include    -c -o engine.o engine.c
gcc -Wall -O  -I ../openssl/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl/libcrypto.a -lpthread -ldl
gcc: ../openssl/libcrypto.a: No such file or directory
make: *** [sscep_static] Error 1

Any help will be appreciated.
Thanks

**Comment by tedescn** [comment]
You don't indicate which OS. But I suspect as the error message suggests, libcrypto.a isn't in "../openssl/"?

If I use "find" in Ubuntu 18.04, libcrypto.a is at "/usr/lib/x86_64-linux-gnu/libcrypto.a".

Can I propose you run "find" within your OS to find this library, then modify your Makefile. 

or 

run "make sscep_dyn", to step over the static version of SSCEP in favour of the dynamic version.

If you look at the Makefile, "make package" is redirected to "make all", where "make all" makes "sscep_static", followed by "sscep_dyn"

Regards
Nigel

**Comment by axhameed** [comment]
Hi Nigel,
Thank you for your reply. My apologies for not mentioning the OS versions. The OS versions are RHEL6 and RHEL7. I ran the find command from the root but I couldn't find library file libcrypto.a.

Thank you,
Amir

**Comment by tedescn** [comment]
Amir,

First I'm no RHEL expert. But have you tried "sudo yum install openssl-static*", this should identify a package for your OSes that contains both libcrypto.a and libssl.a

This may not address the comple problem, but it should install the missing static library (I don't know where on your OS).

Regards
Nigel
