### ISSUE TITLE
Unable to compile with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by jakubmoravek** [certnanny/sscep#94]
Hi,
I am trying to compile sscep (very nice and useful tool, by the way) with OpenSSL 1.1.1 on Raspberry Pi with Raspbian Buster 10.2. I am able to compile it with libssl1.0.0-dev package, but because OpenSSL 1.0 is obsolete and I would like to use the PKCS11 engine to store keys on HW token, I need to use OpenSSL 1.1.1.

After removing line "#include <openssl/asn1_mas.h>" from sscep.h, and running the make command I am getting the following error:

_pkcs7.c: In function ‘get_attribute’:
pkcs7.c:898:26: error: dereferencing pointer to incomplete type ‘X509_ATTRIBUTE’ {aka ‘struct x509_attributes_st’}
   if (OBJ_cmp(x509_attrib->object, asn1_obj) == 0) {_

Any clue how to fix this? Is there any plan to support OpenSSL 1.1.1?

**Comment by tedescn** [comment]
+1
It would be nice to compile with OpenSSL 1.1.1.
This challenge may be beyond my skill set.

Regards
Nigel

**Comment by seho85** [comment]
+1

I would also like to compile with OpenSSL 1.1.1.

I tried to make the changes. And were able to resolve some of the porting to 1.1.1 but I still have some errors. Especially in the ias.c file.

I forked the project. When I managed to solve the problems then I will create a pull request. But I'm quite new to OpenSSL and it could take a while until get that managed.

**Comment by volkc-basf** [comment]
In case anyone is interested to help with testing --> [click here](https://github.com/volkc-basf/sscep) The code compiles with openssl1.1.x, but I still need to figure out if everything is okay now.

**Comment by mbartosch** [comment]
Thanks, let us know if it works. We'd appreciate a pull request if it works out.

**Comment by tedescn** [comment]
Happy to help testing if I can. I will attempt to look at this at the weekend.

**Comment by seho85** [comment]
Thanks for your effort! Unfortunately my first test with WindowsPKI and NDES on Server 2012 R2 failed.

Using dynamically linked version on openssl 1.1.1d

16:41 $ openssl version
OpenSSL 1.1.1d  10 Sep 2019

Output

✔ /tmp/sscep [master|✚ 1…6] 
16:36 $ ./mkrequest -ip 10.0.1.210 2FB50D9A02B943DC
Generating RSA private key, 1024 bit long modulus (2 primes)
............+++++
....+++++
e is 65537 (0x010001)
✔ /tmp/sscep [master|✚ 1…6] 
16:36 $ ./sscep_dyn getca -c ca.crt -u http://10.0.1.121/certsrv/mscep/mscep.dll
✔ /tmp/sscep [master|✚ 1…6] 
16:37 $ ./sscep_dyn enroll -c ca.crt-0  -k local.key -r local.csr -l local.crt -e ca.crt-1 -u http://10.0.1.121/certsrv/mscep/mscep.dll -d 
./sscep_dyn: starting sscep, version 0.6.1
./sscep_dyn: new transaction
./sscep_dyn: transaction id: D41D8CD98F00B204E9800998ECF8427E
./sscep_dyn: hostname: 10.0.1.121
./sscep_dyn: directory: certsrv/mscep/mscep.dll
./sscep_dyn: port: 80
./sscep_dyn:  Read request with transaction id: AF2583B9998A6AE86FCE3D8873C93E38
./sscep_dyn: generating selfsigned certificate
./sscep_dyn: error converting serial
139873861630848:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto/asn1/asn1_lib.c:91:
139873861630848:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto/asn1/tasn_dec.c:1118:
139873861630848:error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:694:

please let me know if i can provide something addtional.

Kind regards,
Sebastian

**Comment by volkc-basf** [comment]
@seho85 : Could you please try it once again? It should be able to convert the serial now. 

c2i_ASN1_INTEGER has been removed with 1.1.x and i thought d2i_ASN1_INTEGER could be used as drop in replacement. But it turned out, openssl needs a slightly different string format to be able to read it successfully.

**Comment by seho85** [comment]
@volkc-basf: It tested it again. It went a little bit further but still failed on "enroll"

This time a attached the output as file instead of flooding the issue :)

Kind regards,
Sebastian

[sscep_enroll_output.txt](https://github.com/certnanny/sscep/files/4134204/sscep_enroll_output.txt)

**Comment by volkc-basf** [comment]
Thank you. I'm sure we'll get this managed.

**Comment by volkc-basf** [comment]
@seho85: Ok, there was an issue with the nonces. Let's see whether it works out now for you.

**Comment by seho85** [comment]
@volkc-basf: Failed again.

[sscep_enroll_output2.txt](https://github.com/certnanny/sscep/files/4134285/sscep_enroll_output2.txt)

**Comment by volkc-basf** [comment]
@seho85 May I ask you to provide me the log produced with the old client, compiled with the old openssl version? That would make it way easier for me to dig out the cause.

**Comment by seho85** [comment]
@volkc-basf: forget about the latest report.. The issue occured because I made some tweaks on the mkrequest script for my windows setup. this tweaks weren't in the mkrequest from your fork.

It's working :)

I tested:

* getca
* enroll

Thanks again for your effort!

Kind regards,
Sebastian

**Comment by volkc-basf** [comment]
Perfect! Thank you for your help with testing! 

@mbartosch: Would you like to verify from your end as well before I hand in a PR?

**Comment by mbartosch** [comment]
Thanks for working on the openssl 1.1 support. 
I am currently checking this against OpenXPKI and facing some problems. Not sure if this is client or server side. Please stand by :)

**Comment by mbartosch** [comment]
It was my mistake. The code seems to be working fine with the OpenXPKI SCEP server.
A pull request would be greatly appreciated. Thanks!

**Comment by volkc-basf** [comment]
This can be closed then.

**Comment by tedescn** [comment]
I am able to compile with OpenSSL-1.1.1c . This is also true for 1.1.1d & 3.0.0-dev

- getca message is successful.
- enroll fails pickup, after pending, where the CA successfully issued a certificate for collection. the feedback is:
..
./sscep-0.6.1/sscep_dyn: scep msg: GET /cgi-bin/pkiclient2.exe?operation=PKIOperation&message=MIIJ4gYJK......%3D%0A HTTP/1.0
./sscep-0.6.1/sscep_dyn: server returned status code 200
./sscep-0.6.1/sscep_dyn: MIME header: x-pki-message
./sscep-0.6.1/sscep_dyn: cannot find data from http reply

This may be a serverside error for me to investigate on a piloting platform, where an older test client exhibits the same issues.

**Comment by tedescn** [comment]
For infromation I'm told the matching backend error is:

ERROR 02/01/20 18:39:53  csl03802web03(45180/0)  processpki.c(3043):Bad GetCertInitial Message Encoding

This is consistent with the client messages. This is against a Verisign/Symantec/Digicert SCEP responder. I'll start looking at this during the week.

**Comment by tedescn** [comment]
Regards testing, my old client now works. Issue was I need to revoke previous certificate, before re-issuing.

See screenshot of good (left), bad (right) scep responder GertCertInitial message. As an inital observation the "issuer" and "subject" information appear reversed. I'm not sure I yet understand why.
  
![image](https://user-images.githubusercontent.com/10996727/73687212-755ec900-46c1-11ea-8673-3ee4dfc1442b.png)

**Comment by tedescn** [comment]
I may be getting closer? See attached enroll trace (Side note, shouldn't files VERSION and sscep.h be aligned to 0.7?). 

I'm wondering if I'm hitting the sscep.c if statement on line 990? I'm thinking I need to add a printf message to dertermine?

See attached debug log
[Bad log.docx](https://github.com/certnanny/sscep/files/4150356/Bad.log.docx)

Note: the SCEP responder is from VeriSign/Symantec/DigiCert origin.

**Comment by tedescn** [comment]
@mbartosch I added an fprintf statement on line 995 of sscep.c and can now confirm I'm hitting the "Verisign Onsite returns strange reply..." issue identified. 

Dumb question, is there a way to re-learn the original cause and resolution reagards this if statement?

alternatively, I need to work out how to pull the request messages apart, where I don't have access to the Issuing CA private key. Any suggestion?

Note, in the screen shot above, the backend log indicates a reversal of the message data somewhere. i.e. issuer and subject have somehow become reversed in "issuerAndSubject" - is this likely the cause? 

From SCEP drafts 23 & Gutmann 14.

   issuerAndSubject ::= SEQUENCE {
       issuer     Name,
       subject    Name
       }

**Comment by oliwel** [comment]
> alternatively, I need to work out how to pull the request messages apart, where I don't have access to the Issuing CA private key. Any suggestion?

I don't think you need to - you can disassemble the inner and outer PKCS#7 structure using e.g. openssl asn1parse. The only thing that would be opaque is the encrypted payload but this is only the serialized PKCS#10 data.

Did this responder work with the old sscep code? A common problem in the past was that sscep used the wrong certificate to encrypt the payload? It just takes the first certificate from the getca response but we have seen responders sending the issuing ca / root ca first which results in the payload being encrypted with the issuing / root certificate.

**Comment by tedescn** [comment]
Having gone through both good and bad traces it appear I’m comparing apples and oranges at this time.

The good older client today uses sha1/3des, the bad newer client uses md5/des.

The first takes on the output of the CA_Capabilities file, while the second currently doesn’t.The PKCS7 outers differ as follows at the foot:

**Good 3des/sha1**
..
..
 2102:d=7  hl=2 l=  10 prim: OBJECT            :2.16.840.1.113733.1.9.5
 2114:d=7  hl=2 l=  18 cons: SET               
 2116:d=8  hl=2 l=  16 prim: OCTET STRING      [HEX DUMP]:CA2836E5B07616BAC1F3B26BC09A2180
 2134:d=6  hl=2 l=  35 cons: SEQUENCE          
 2136:d=7  hl=2 l=   9 prim: OBJECT            :messageDigest
 2147:d=7  hl=2 l=  22 cons: SET               
 2149:d=8  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:BBEF02363FB409A0E3CEF57D70EB9A3CB08EEBE3
 2171:d=6  hl=2 l=  48 cons: SEQUENCE          
 2173:d=7  hl=2 l=  10 prim: OBJECT            :2.16.840.1.113733.1.9.7
 2185:d=7  hl=2 l=  34 cons: SET               
 2187:d=8  hl=2 l=  32 prim: PRINTABLESTRING   :C3CA12B9AC0F1BDFBC455691653CCB35
 2221:d=5  hl=2 l=  13 cons: SEQUENCE          
 2223:d=6  hl=2 l=   9 prim: OBJECT            :rsaEncryption
..
..

**Bad des/md5**

..
..
 2187:d=7  hl=2 l=   9 prim: OBJECT            :messageDigest
 2198:d=7  hl=2 l=  18 cons: SET               
 2200:d=8  hl=2 l=  16 prim: OCTET STRING      [HEX DUMP]:974C654E6FC9B71348942596E4FFCECA
 2218:d=6  hl=2 l=  32 cons: SEQUENCE          
 2220:d=7  hl=2 l=  10 prim: OBJECT            :2.16.840.1.113733.1.9.5
 2232:d=7  hl=2 l=  18 cons: SET               
 2234:d=8  hl=2 l=  16 prim: OCTET STRING      [HEX DUMP]:EFD07B74C0A25C9D4511A46E6032BB78
 2252:d=6  hl=2 l=  48 cons: SEQUENCE          
 2254:d=7  hl=2 l=  10 prim: OBJECT            :2.16.840.1.113733.1.9.7
 2266:d=7  hl=2 l=  34 cons: SET               
 2268:d=8  hl=2 l=  32 prim: PRINTABLESTRING   :718EEB661EB7ED79E2BE524CC687B535
 2302:d=5  hl=2 l=  13 cons: SEQUENCE          
 2304:d=6  hl=2 l=   9 prim: OBJECT            :rsaEncryption
..
..

I’ll modify the newer script at the weekend, and retry. If this works I’ll also attempt to break the old by not pulling in the CA_Capabilities file, it should then use des/md5 by default.

It doesn’t feel like this correlates with the “Issuer_AND_Subject” difference identified above on the server side, however I feel I have to follow the evidence and repeat.

Regards
Nigel

**Comment by tedescn** [comment]
For information both good and bad now use des3/sha1 - bad continues to fail PENDING pick-up via GetCertInitial. The outer PKCS7 messages, now shares an identical message format.

I will look again at GetCertInitial, triggered as a result of the scep responder's PENDING response to enrolment.

Can I ask a dumb question:
1. Do others exercise the GetCertInitial option?

I may be looking at a couple of issues:

1. looking at sscep.c code between lines, 845 & 872 IssuerAndSubject appear to be reversed, I believe this was done to support the "not_enroll" condition that generates IssuerAndSerial? This observation likely identifies why the IssuerAndSubject appear reversed within the SCEP responder logs - see graphic above.
2. I'm still trying to work out the encoding of the good IssuerAndSubject which also differs from the bad. The bad is plain ascii, regards the bad, the name of the name value pairs is something else (tbd). Any ideas?

Regards
Nigel

**Comment by tedescn** [comment]
Reading the code last night, I believe I have found a typo, I will test over the weekend.

Within the ias.c file the Issuer & Subject are reversed on lines 18 and 19. I believe these two lines need flipping.

I'm expecting this addresses the the IssuerAndSubject structure order issue indicated above. I don't know that it addresses the encoding difference indicated in the above graphic.

Regards
Nigel

**Comment by tedescn** [comment]
> 
> 
> > alternatively, I need to work out how to pull the request messages apart, where I don't have access to the Issuing CA private key. Any suggestion?
> 
> I don't think you need to - you can disassemble the inner and outer PKCS#7 structure using e.g. openssl asn1parse. The only thing that would be opaque is the encrypted payload but this is only the serialized PKCS#10 data.
> 
> Did this responder work with the old sscep code? A common problem in the past was that sscep used the wrong certificate to encrypt the payload? It just takes the first certificate from the getca response but we have seen responders sending the issuing ca / root ca first which results in the payload being encrypted with the issuing / root certificate.

I missed the last part of this response. The SCEP responders in question answers for many different PKIs using the -i indetifier option. It is because of this workload and seperation the inital response is PENDING, allowing the SCEP responder to process the request for future pick-up. As a result GetCertInitial isn't optional for us.

**Comment by tedescn** [comment]
I believe the differences between old and new GetCertInitial included the following differences:

1.	Issuer and Subject have become reversed within definition ias.c, I reversed lines18 & 19.
2.	I believe the original IssuerAndSubject (IAS) values were the ASN1 structure, rather than the x509 structure?
3.	The new IAS structure include labels “P K C S 7 _ I S S U E R _ A N D _ S U B J E C T :”, “i s s u e r :” And “s u b j e c t :”?
4.	I’ve yet to work out how to print the either the ias, or pkcs7 inner of getcertinital?

I include below the backend received, GetCertInitial pkcs7 inners of good (old version), bad (new version).

I have to admit to be struggling to address. 

**Good – GetCertInitial request**

-- 02/03 09:54:54 [6] Receive message "ipsec receive pkcs7 message" (2007 bytes) from child 3 (Pid = 17777)
-- 02/03 09:54:54 Response(4)
<<          2 0 0 081c5 0 J 10b 0090603 U04061302 G B 1 ' 0 %0603 U040a13
<<       1e B r i t i s h   T e l e c o m m u n i c a t i o n s   p l c 1
<<       12 0100603 U04031309 B T   P o C   C A 0 w 10b 0090603 U04061302
<<        G B 10f 00d0603 U04081306 L o n d o n 10f 00d0603 U04071306 L o
<<        n d o n 1 ' 0 %0603 U040a131e B r i t i s h   T e l e c o m m u
<<        n i c a t i o n s   p l c 11d 01b0603 U04031314 m a r k - t e s
<<        t . p o c . b t . c o m       0       0       1       7       0
<<              1 0     1 6a8 -b818c6 Jd2 y g0c82b8 pd4f1b2 1 7 4 2 M I I
<<        E 7 D C C A t S g A w I B A g I Q E Z L g E / t f p X 0 I s O k
<<        M i a V 3 / T A N B g k q h k i G 9 w 0 B A Q s F A D B P0d0a M
<<        Q s w C Q Y D V Q Q G E w J H Q j E n M C U G A 1 U E C h M e Q
<<        n J p d G l z a C B U Z W x l Y 2 9 t b X V u a W N h d G l v0d
<<       0a b n M g c G x j M R c w F Q Y D V Q Q D E w 5 C V C B Q b 0 M
<<        g U m 9 v d C B D Q T A e F w 0 x N D E y M j I w M D A w M D B

**Bad – GetCertInitial request**

-- 02/07 18:55:28 Response(6)
<<          2 6 4 P K C S 7 _ I S S U E R _ A N D _ S U B J E C T :  0a
<<          i s s u e r :   C = G B ,   O = B r i t i s h   T e l e c o m
<<        m u n i c a t i o n s   p l c ,   C N = B T   P o C   C A0a
<<        s u b j e c t :   C = G B ,   S T = L o n d o n ,   L = L o n d
<<        o n   T o w n ,   O = B r i t i s h   T e l e c o m m u n i c a
<<        t i o n s   p l c ,   C N = 0 0 0 0 D B 0 0 0 0 0 0 0 0 0 1 . p
<<        o c . b t . c o m / u n s t r u c t u r e d N a m e = 0 0 0 0 D
<<        B 0 0 0 0 0 0 0 0 0 1 . p o c . b t . c o m / s e r i a l N u m
<<        b e r = 0 0 0 0 0 0 10a       0       0       1       7       0
<<              1 0

**Comment by tedescn** [comment]
I now do understand the problem, but don't yet have the solution. The previous solutions capture the "issuer" and "subject" data in asn1 der encoded format. The current solution captures the same data in its x509 format. I can reproduce the required format with openssl ans1parse with the -strparse offset. This requires an inital visual scan to determine the offset value of the asn1sequence of sets.

In a perfect world I would like to use openssl asn1parse "-item name" option to pull out the issuer and subject sequences.  i) I get the feeling this "-item" directive is imature, currently, and ii) I'm struggling to locate possible name values that indicate issuer, or subject.

**Comment by tedescn** [comment]
thankyou @ovk for #106 and #107 pull request.

Your pull request, and the reversal of lines 18 & 19 in the asn1 sequence of ias.c fixed my issues. Much appreciated, as I wouldn't have got here myself.
